version: "3.7"
services:
  transmission:
    image: linuxserver/transmission:2.94-r2-ls35
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      # Do not expose port 9091; will proxy it via http.
      - 51413:51413
      - 51413:51413/udp
    environment:
      - USER=admin
      - PASS=pass

  http:
    image: abiosoft/caddy:1.0.3-no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      # Mount the downloads/ folder into caddy's default sites root (/srv) so
      # that we can retrieve completed downloads via http.
      - ./transmission/downloads:/srv/downloads
    ports:
      - 80:80
    environment:
      - USER=admin
      - PASS=pass
