version: "3.7"
services:
  transmission:
    image: linuxserver/transmission:latest
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      # Do not expose port 9091; will proxy it via http.
      - 51413:51413
      - 51413:51413/udp
    env_file: .env

  http:
    image: abiosoft/caddy:latest
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      # Mount the downloads/ folder into caddy's default sites root (/srv) so
      # that we can retrieve completed downloads via http.
      - ./transmission/downloads:/srv/downloads
    ports:
      # Set $HTTP_PORT to override; defaults to port 80 on host.
      - ${HTTP_PORT:-80}:80
    env_file: .env
