version: "3.7"
services:
  transmission:
    image: linuxserver/transmission
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    ports:
      # Do not expose port 9091; will proxy it via http.
      - 51413:51413
      - 51413:51413/udp

  http:
    image: abiosoft/caddy:1.0.3-no-stats
    volumes:
      # /srv is default sites root from caddy container.
      - ./transmission:/srv
      - ./http/Caddyfile:/etc/Caddyfile
    ports:
      - 2095:2095
